export const LOGIN = "LOGIN/LONIN"

export const SET_SSID = "LOGIN/SET_SSID"

export const CHANGE_LOGIN_STATUS = "LOGININFO/LOGIN_STATUS"

export const GET_LOGOIN_INFO = "LOGININFO/GET_LOGOIN_INFO"
export const SET_LOGOIN_INFO = "LOGININFO/SET_LOGOIN_INFO"


export const SET_TOP_MENU = "TOPMENU/SET_TOP_MENU"

export const SET_SIDE_MENU = "TOPMENU/SET_SIDE_MENU"

export const SET_MENU_ACTIVE = "TOPMENU/SET_MENU_ACTIVE"